greeting: 'Hello from client'

db:
  connection: mysql
  host: localhost
  port: 3306

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      base-path: '/manage'
      exposure:
        include: '*'

spring:
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true
      name: config-client
  application:
    name: config-client
  config:
    use-legacy-processing: true

server:
  port: 8080