spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Emil-Wozniak/config.git
          username: emil.wozniak.591986@gmail.com
          password: n8WRwg56Mqbe

server:
  port: 8888